# Generated by Django 5.0.1 on 2024-03-12 12:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_alter_aluno_engajamento_familia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='historico_academico',
            field=models.FileField(blank=True, upload_to='alunos/historicos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
