# Generated by Django 5.0.1 on 2024-03-11 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
        ('responsaveis', '0002_remove_responsavelprofile_parentesco'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsavelprofile',
            name='dependentes',
            field=models.ManyToManyField(blank=True, related_name='responsaveis', to='alunos.aluno'),
        ),
    ]
