# Generated by Django 5.0.2 on 2024-03-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsaveis', '0003_responsavelprofile_dependentes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('is_valid', models.BooleanField(default=True)),
            ],
        ),
    ]
