# Generated by Django 5.0.2 on 2024-02-26 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('denuncia', '0004_denuncia_telefone_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedidaTomada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo_acao', models.CharField(blank=True, max_length=30, null=True)),
                ('denuncia_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='denuncia.denuncia')),
            ],
        ),
    ]
