# Generated by Django 5.0.1 on 2024-01-24 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relato', models.CharField(max_length=500)),
                ('v_fisica', models.CharField(max_length=10)),
                ('v_verbal', models.CharField(max_length=10)),
                ('bullying', models.CharField(max_length=10)),
                ('assedio', models.CharField(max_length=10)),
                ('recorrencia', models.CharField(max_length=50)),
                ('data_ocorrido', models.DateTimeField()),
                ('lugar', models.CharField(max_length=50)),
            ],
        ),
    ]
