# Generated by Django 5.0.1 on 2024-02-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='assedio',
            field=models.CharField(choices=[('yes', 'Sim'), ('no', 'Não')], max_length=10),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='bullying',
            field=models.CharField(choices=[('yes', 'Sim'), ('no', 'Não')], max_length=10),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='v_fisica',
            field=models.CharField(choices=[('yes', 'Sim'), ('no', 'Não')], max_length=10),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='v_verbal',
            field=models.CharField(choices=[('yes', 'Sim'), ('no', 'Não')], max_length=10),
        ),
    ]
