# Generated by Django 5.0.1 on 2024-02-07 21:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncia', '0002_alter_denuncia_assedio_alter_denuncia_bullying_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='data_denuncia',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='denuncia',
            name='matricula',
            field=models.IntegerField(default=113),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='denuncia',
            name='telefone_1',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='v_domestica',
            field=models.CharField(choices=[('yes', 'Sim'), ('no', 'Não')], default='no', max_length=10),
            preserve_default=False,
        ),
    ]
