# Generated by Django 5.0.1 on 2024-02-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncia', '0003_denuncia_data_denuncia_denuncia_matricula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='telefone_2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
