# Generated by Django 5.0.2 on 2024-03-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncia', '0004_denuncia_telefone_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='pontuacao',
            field=models.FloatField(default=0.0),
        ),
    ]
