# Generated by Django 5.0.2 on 2024-03-08 13:09

import denuncia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncia', '0005_denuncia_pontuacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='arquivo_1',
            field=models.FileField(blank=True, null=True, upload_to=denuncia.models.upload_file_formater),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='arquivo_2',
            field=models.FileField(blank=True, null=True, upload_to=denuncia.models.upload_file_formater),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='arquivo_3',
            field=models.FileField(blank=True, null=True, upload_to=denuncia.models.upload_file_formater),
        ),
    ]
