# Generated by Django 5.0.1 on 2024-03-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0003_alter_aluno_historico_academico'),
        ('denuncia', '0006_denuncia_arquivo_1_denuncia_arquivo_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='praticantes',
            field=models.ManyToManyField(blank=True, related_name='denuncia_praticante', to='alunos.aluno'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='titulo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='vitimas',
            field=models.ManyToManyField(blank=True, related_name='denuncia_vitima', to='alunos.aluno'),
        ),
    ]
